---
language: python
python: "2.7"

env:
  global:
    - ROLE_NAME: stackdriver

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME apham0001.$ROLE_NAME
  - cd apham0001.$ROLE_NAME
  - touch tests/application_default_credentials.json

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
