---
- name: Stat mysql.conf.
  stat:
    path: "{{ stackdriver_plugins_dir }}/mysql.conf"
  register: stackdriver_mysql_conf

- name: install dependency for mysql.conf.
  package:
    name: libmariadbclient18
    state: present
  when: stackdriver_mysql_conf.stat.exists

- name: Add status vhost in Apache.
  template:
    src: "status.conf.j2"
    dest: "{{ apache_sites_available }}/status.conf"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Enable status vhost.
  file:
    src: "{{ apache_sites_available }}/status.conf"
    dest: "{{ apache_sites_enabled }}/status.conf"
    state: link
